apps/marketing/src/app/page.tsx
=> fix: unwanted scrollbars

apps/marketing/src/app/layout.tsx, apps/marketing/src/app/page.tsx, apps/marketing/src/components/landind-page.tsx, packages/ui/index.ts, packages/ui/theme-provider.tsx
Fix hydration errors with the theme provider
=> fix: resolve hydration and other errors

apps/web/prisma/migrations/20240527202531_add_is_verifying/migration.sql, apps/web/prisma/schema.prisma, apps/web/src/app/(dashboard)/domains/[domainId]/page.tsx, apps/web/src/app/(dashboard)/domains/add-domain.tsx, apps/web/src/server/api/routers/domain.ts, apps/web/src/server/service/domain-service.ts
=> Add verify domain button

apps/web/package.json, apps/web/src/env.js, apps/web/src/server/public-api/auth.ts, packages/sdk/package.json, packages/ui/src/spinner.tsx, pnpm-lock.yaml
=> Add API rate limit

apps/web/src/app/(dashboard)/api-keys/add-api-key.tsx, apps/web/src/app/(dashboard)/api-keys/api-list.tsx, apps/web/src/app/(dashboard)/api-keys/delete-api-key.tsx, apps/web/src/server/api/routers/api.ts, apps/web/src/server/service/api-service.ts
=> Add delete API key

apps/docs/community-sdk/python.mdx, apps/docs/mint.json
=> feat: Created a new Python library and added the documentation for the same

apps/docs/get-started/local.mdx, apps/web/package.json, apps/web/prisma/schema.prisma, apps/web/src/env.js, apps/web/src/server/db.ts, pnpm-lock.yaml
=> perf: Enable Prisma Optimize

apps/web/src/components/settings/AddSesSettings.tsx, apps/web/src/server/service/email-queue-service.ts
=> fix queue failing for certain edge cases

apps/docs/get-started/smtp.mdx, apps/docs/introduction.mdx, apps/docs/mint.json, apps/smtp-server/src/usage.js
=> docs: Added SMTP docs

apps/web/package.json, apps/web/prisma/migrations/20240820093529_add_schedule/migration.sql, apps/web/prisma/migrations/20240820093931_add_cancelled/migration.sql, apps/web/prisma/schema.prisma, apps/web/src/app/(dashboard)/emails/cancel-email.tsx, apps/web/src/app/(dashboard)/emails/edit-schedule.tsx, apps/web/src/app/(dashboard)/emails/email-details.tsx, apps/web/src/app/(dashboard)/emails/email-list.tsx, apps/web/src/server/api/routers/email.ts, apps/web/src/server/public-api/api/emails/cancel-email.ts, apps/web/src/server/public-api/api/emails/send-email.ts, apps/web/src/server/public-api/api/emails/update-email.ts, apps/web/src/server/public-api/index.ts, apps/web/src/server/service/email-queue-service.ts, apps/web/src/server/service/email-service.ts, apps/web/src/server/service/ses-hook-parser.ts, apps/web/src/types/index.ts, packages/ui/package.json, packages/ui/src/command.tsx, packages/ui/src/input.tsx, pnpm-lock.yaml
=> Add schedule api

apps/web/package.json, apps/web/src/app/(dashboard)/campaigns/[campaignId]/edit/page.tsx, apps/web/src/env.js, apps/web/src/server/api/routers/campaign.ts, apps/web/src/server/nanoid.ts, apps/web/src/server/service/storage-service.ts, docker/dev/compose.yml, docker/prod/compose.yml, packages/email-editor/src/editor.tsx, packages/email-editor/src/extensions/ImageExtension.tsx, packages/email-editor/src/extensions/SlashCommand.tsx, packages/email-editor/src/extensions/index.ts, packages/email-editor/src/nodes/button.tsx, packages/email-editor/src/nodes/image-resize.tsx, packages/email-editor/tsconfig.lint.json, pnpm-lock.yaml, turbo.json
=> feat: add upload image option

apps/docs/api-reference/contacts/delete-contact.mdx, apps/docs/api-reference/contacts/upsert-contact.mdx, apps/docs/api-reference/openapi.json, apps/docs/mint.json, apps/web/src/server/public-api/api/contacts/delete-contact.ts, apps/web/src/server/public-api/api/contacts/upsert-contact.ts, packages/sdk/src/contact.ts, packages/sdk/types/schema.d.ts
This PR adds upsert and delete to contacts, so they can be managed a bit more easily via the API.
Feel free to make any changes as this is just a quick PR.
Thanks,
8x4
=> feat: add upsert and delete to contacts

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/marketing.yml, .github/ISSUE_TEMPLATE/smtp.yml
Basic introduction to issue templates for bug reports, marketing issues, and SMTP issues to streamline the process of filing and managing these types of issues. The most important changes include the addition of structured templates with predefined fields and validation requirements.
Related to https://github.com/unsend-dev/unsend/issues/81
=> Issue templates

apps/web/src/server/api/routers/email.ts
It performs explicit type cast to fix the issue #92
=> [Fix] : email list status filter

apps/docs/get-started/create-aws-credentials.mdx, apps/docs/get-started/local.mdx, apps/docs/get-started/self-hosting.mdx
HI, thanks for this great project.
I followed the local installation guide and I found a mismatch on the env variables names.
This PR is to align the docs with the right names.
=> fix(docs): adjust env variables

apps/web/next.config.js, apps/web/src/app/(dashboard)/contacts/[contactBookId]/contact-list.tsx, apps/web/src/utils/gravatar-utils.ts
#89 
Fetches the avatar from gravatar.com using a sha-256(secure version) hash for the email of contact.
=> [Feat]: Gravatar for contacts

apps/web/next-env.d.ts, apps/web/src/app/(dashboard)/dev-settings/api-keys/add-api-key.tsx
Was building domains API found this small fix
=> fix: create api key button

.gitignore, apps/web/src/app/(dashboard)/dashboard/dashboard-chart.tsx
=> refactor: shows 0 instead of nan for new users

.env.example, .env.selfhost.example, .gitignore, apps/web/src/app/(dashboard)/dev-settings/smtp/page.tsx, apps/web/src/env.js, docker/prod/compose.yml
=> refactor: dynamic SMTP for self host

apps/web/src/server/public-api/api/emails/send-email.ts, apps/web/src/server/service/email-service.ts
=> allow text to be nullable

CONTRIBUTION.md
This PR adds a `CONTRIBUTION.md` file to provide detailed guidelines for contributors. It includes setup instructions, contribution workflow, coding standards, and community details to encourage participation in the Unsend project.
Related to #71
=> Add CONTRIBUTION.md with guidelines for contributors

apps/web/src/app/(dashboard)/dashboard/dashboard-filters.tsx
fixed responsiveness of dashboard topbar
before
after
=> ui-fix topbar

docker/dev/compose.yml
Fixed docker setup in dev . Had wrong credentials
=> fixed docker setup for psql
